using System;

namespace VspEngine
{
	public abstract class GameObject
	{
		/// <summary>
		/// Non-negative integer handle GENERATED by the C++ host to address
		/// this object (0 = invalid).
		/// </summary>
		public uint InstanceID { get; internal set; }

		/// <summary>
		/// Opaque pointer to this managed object (its GCHandle). The C++ host
		/// passes it back on every lifecycle call, which lets the bridge work
		/// without maintaining any instance registry of its own.
		/// </summary>
		public IntPtr NativePtr { get; internal set; }

		public uint GetInstanceID()
		{
			return InstanceID;
		}
	}
}
