param(
    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"

# ---- Locate glslc.exe ---------------------------------------------------------
$candidates = @()
if ($env:VULKAN_SDK) {
    $candidates += Join-Path $env:VULKAN_SDK "Bin\glslc.exe"
}
$candidates += @(Get-ChildItem "C:\VulkanSDK\*\Bin\glslc.exe" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName)

$glslc = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $glslc) {
    throw "glslc.exe not found - install the Vulkan SDK or set VULKAN_SDK."
}
Write-Host "CompileShaders: using $glslc"

$shaderSourceDir = Split-Path -Parent $MyInvocation.MyCommand.Path
# Bindless (Vulkan 1.3) is the only supported rendering path, so only its
# shaders are compiled and embedded.
$shaderNames = @(
    "TriangleBindless.vert",
    "TriangleBindless.frag"
)

# ---- Compile each shader to a temporary SPIR-V file --------------------------
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Auto-generated by CompileShaders.ps1 - do not edit.")
$lines.Add("#pragma once")
$lines.Add("")
$lines.Add("#include <cstdint>")
$lines.Add("")
$lines.Add("namespace Vsp")
$lines.Add("{")
$lines.Add("    namespace Shaders")
$lines.Add("    {")

foreach ($shaderName in $shaderNames) {
    $shaderPath = Join-Path $shaderSourceDir $shaderName
    $spvPath = Join-Path $env:TEMP ("vsp_" + $shaderName + ".spv")

    & $glslc $shaderPath -o $spvPath
    if ($LASTEXITCODE -ne 0) {
        throw "glslc failed to compile $shaderName"
    }

    $bytes = [System.IO.File]::ReadAllBytes($spvPath)
    if (($bytes.Length % 4) -ne 0) {
        throw "SPIR-V size for $shaderName is not 4-byte aligned"
    }

    $wordCount = [int]($bytes.Length / 4)
    $symbolName = "k_" + $shaderName.Replace(".", "_") + "Spv"
    $sizeName = "k_n" + $shaderName.Replace(".", "_") + "SpvSize"

    $lines.Add("        inline const uint32_t $symbolName[] = {")

    $chunks = New-Object System.Collections.Generic.List[string]
    for ($wordIndex = 0; $wordIndex -lt $wordCount; $wordIndex++) {
        $word = [System.BitConverter]::ToUInt32($bytes, $wordIndex * 4)
        $chunks.Add(("0x{0:X8}" -f $word))
        if ($chunks.Count -eq 8) {
            $lines.Add("            " + ($chunks -join ", ") + ",")
            $chunks.Clear()
        }
    }
    if ($chunks.Count -gt 0) {
        $lines.Add("            " + ($chunks -join ", "))
    }
    $lines.Add("        };")
    $lines.Add("        inline constexpr uint32_t $sizeName = $wordCount;")
    $lines.Add("")
    Remove-Item $spvPath -Force
}

$lines.Add("    }")
$lines.Add("}")

$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}
[System.IO.File]::WriteAllLines($OutputPath, $lines, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "CompileShaders: wrote $OutputPath"
