#pragma once

#include <cstdint>

#include <nethost.h>
#include <hostfxr.h>
#include <coreclr_delegates.h>

#include "Classes/Object.h"

namespace Vsp
{
	// -------------------------------------------------------------------------
	// BridgeFunctions
	// -------------------------------------------------------------------------
	// Raw function pointers into the managed bridge (VspEngine.NativeBridge in
	// VspEngine.dll), fetched through hostfxr's
	// load_assembly_and_get_function_pointer. Every managed entry point is
	// marked [UnmanagedCallersOnly], so the pointers follow the platform
	// calling convention (CORECLR_DELEGATE_CALLTYPE == the native default on x64).
	//
	// Ownership model: the C++ host GENERATES the non-negative InstanceID and
	// receives back an opaque native handle (the managed object's GCHandle as
	// an IntPtr). Lifecycle calls pass that handle - the managed bridge keeps
	// no instance registry of its own.
	//
	// Object model: creating a script instance also creates its native scene
	// objects (a GameObject with its Transform plus the script Component), and
	// the handles are handed to the managed instance, which stores nothing but
	// those handles.
	//
	// Assembly model: the bridge lives in the engine's managed runtime
	// (VspEngine.dll); LoadGameAssembly loads the game Assembly (Assembly.dll)
	// that holds the user scripts and CallRenderFrame renders one frame through
	// the managed frame driver (VspEngine.Rendering.RenderFrameDriver).
	// -------------------------------------------------------------------------

	namespace ManagedBridgeDetail
	{
		// Fills a native array of bridge entry-point pointers. Every pointer
		// comes from the SINGLE loaded copy of VspEngine.dll (loading the
		// assembly once per entry point would create several copies with
		// separate static state, so the whole table is collected in one
		// call from the one loaded copy).
		using GetBridgeFunctionTableFn = void (CORECLR_DELEGATE_CALLTYPE*)(
			void** ppFunctionTable);

		// Loads the game Assembly containing the user scripts into the
		// bridge's own load context (the context that holds the single
		// VspEngine.dll copy). Returns 1 on success, 0 on failure.
		using LoadGameAssemblyFn = int32 (CORECLR_DELEGATE_CALLTYPE*)(
			const char_t* pAssemblyPathUtf16);

		// Creates one script instance. nInstanceId is generated by the C++
		// host; the returned handle addresses the managed object afterwards.
		// The scene handles address the native data the managed instance is a
		// reference handle for.
		using CreateInstanceFn = void* (CORECLR_DELEGATE_CALLTYPE*)(
			int32 nInstanceId,
			uint32 uGameObjectHandle,
			uint32 uTransformHandle,
			uint32 uComponentHandle,
			const char_t* pTypeNameUtf16);

		// Script type enumeration (the host decides what to instantiate).
		using GetScriptTypeCountFn = int32 (CORECLR_DELEGATE_CALLTYPE*)();
		using GetScriptTypeNameFn = void (CORECLR_DELEGATE_CALLTYPE*)(
			int32 nTypeIndex,
			char_t* pBufferUtf16,
			int32 nBufferCapacityUnits);

		// Lifecycle calls, addressed through the opaque managed handle.
		using CallOnInitFn = void (CORECLR_DELEGATE_CALLTYPE*)(void* pManagedHandle);
		using CallOnStartFn = void (CORECLR_DELEGATE_CALLTYPE*)(void* pManagedHandle);
		using CallOnUpdateFn = void (CORECLR_DELEGATE_CALLTYPE*)(void* pManagedHandle);
		using DestroyInstanceFn = void (CORECLR_DELEGATE_CALLTYPE*)(void* pManagedHandle);

		// Renders one frame through the managed frame driver: the engine's frame
		// is opened, the active pipeline records its passes inside it - building
		// its draw list from the native scene - and everything is recorded
		// through the wrapped graphics API.
		using CallRenderFrameFn = void (CORECLR_DELEGATE_CALLTYPE*)();

		// Lets the managed render pipeline release the graphics resources it
		// created before the backend shuts down.
		using ReleaseRenderPipelineFn = void (CORECLR_DELEGATE_CALLTYPE*)();
	}

	struct BridgeFunctions
	{
		ManagedBridgeDetail::GetBridgeFunctionTableFn GetBridgeFunctionTable = nullptr;
		ManagedBridgeDetail::LoadGameAssemblyFn LoadGameAssembly = nullptr;
		ManagedBridgeDetail::CreateInstanceFn CreateInstance = nullptr;
		ManagedBridgeDetail::GetScriptTypeCountFn GetScriptTypeCount = nullptr;
		ManagedBridgeDetail::GetScriptTypeNameFn GetScriptTypeName = nullptr;
		ManagedBridgeDetail::CallOnInitFn CallOnInit = nullptr;
		ManagedBridgeDetail::CallOnStartFn CallOnStart = nullptr;
		ManagedBridgeDetail::CallOnUpdateFn CallOnUpdate = nullptr;
		ManagedBridgeDetail::DestroyInstanceFn DestroyInstance = nullptr;
		ManagedBridgeDetail::CallRenderFrameFn CallRenderFrame = nullptr;
		ManagedBridgeDetail::ReleaseRenderPipelineFn ReleaseRenderPipeline = nullptr;
	};
}
