#pragma once

#include <cstdint>

#include <nethost.h>
#include <hostfxr.h>
#include <coreclr_delegates.h>

namespace Vsp
{
	// -------------------------------------------------------------------------
	// BridgeFunctions
	// -------------------------------------------------------------------------
	// Raw function pointers into the managed bridge (VspEngine.NativeBridge in
	// VspEngine.dll), fetched through hostfxr's
	// load_assembly_and_get_function_pointer. Every managed entry point is
	// marked [UnmanagedCallersOnly], so the pointers follow the platform
	// calling convention (CORECLR_DELEGATE_CALLTYPE == the native default on x64).
	//
	// Ownership model: the C++ host GENERATES the non-negative InstanceID and
	// receives back an opaque native handle (the managed object's GCHandle as
	// an IntPtr). Lifecycle calls pass that handle - the managed bridge keeps
	// no instance registry of its own.
	//
	// Assembly model: the bridge lives in the engine's managed runtime
	// (VspEngine.dll); LoadGameAssembly loads the game Assembly (Assembly.dll)
	// that holds the user scripts, and CallRenderFlow drives the managed
	// render flow once per frame.
	// -------------------------------------------------------------------------

	namespace ManagedBridgeDetail
	{
		// Fills a native array of bridge entry-point pointers. Every pointer
		// comes from the SINGLE loaded copy of VspEngine.dll (loading the
		// assembly once per entry point would create several copies with
		// separate static state, so the whole table is collected in one
		// call from the one loaded copy).
		using GetBridgeFunctionTableFn = void (CORECLR_DELEGATE_CALLTYPE*)(
			void** ppFunctionTable);

		// Loads the game Assembly containing the user scripts into the
		// bridge's own load context (the context that holds the single
		// VspEngine.dll copy). Returns 1 on success, 0 on failure.
		using LoadGameAssemblyFn = int32 (CORECLR_DELEGATE_CALLTYPE*)(
			const char_t* pAssemblyPathUtf16);

		// Creates one script instance. nInstanceId is generated by the C++
		// host; the returned handle addresses the managed object afterwards.
		using CreateInstanceFn = void* (CORECLR_DELEGATE_CALLTYPE*)(
			int32 nInstanceId,
			const char_t* pTypeNameUtf16);

		// Script type enumeration (the host decides what to instantiate).
		using GetScriptTypeCountFn = int32 (CORECLR_DELEGATE_CALLTYPE*)();
		using GetScriptTypeNameFn = void (CORECLR_DELEGATE_CALLTYPE*)(
			int32 nTypeIndex,
			char_t* pBufferUtf16,
			int32 nBufferCapacityUnits);

		// Lifecycle calls, addressed through the opaque managed handle.
		using CallOnInitFn = void (CORECLR_DELEGATE_CALLTYPE*)(void* pManagedHandle);
		using CallOnStartFn = void (CORECLR_DELEGATE_CALLTYPE*)(void* pManagedHandle);
		using CallOnUpdateFn = void (CORECLR_DELEGATE_CALLTYPE*)(void* pManagedHandle);
		using DestroyInstanceFn = void (CORECLR_DELEGATE_CALLTYPE*)(void* pManagedHandle);

		// Runs the managed render flow for one frame; the primary script's
		// InstanceID is passed in (0 = no primary instance).
		using CallRenderFlowFn = void (CORECLR_DELEGATE_CALLTYPE*)(uint32 uPrimaryInstanceId);
	}

	struct BridgeFunctions
	{
		ManagedBridgeDetail::GetBridgeFunctionTableFn GetBridgeFunctionTable = nullptr;
		ManagedBridgeDetail::LoadGameAssemblyFn LoadGameAssembly = nullptr;
		ManagedBridgeDetail::CreateInstanceFn CreateInstance = nullptr;
		ManagedBridgeDetail::GetScriptTypeCountFn GetScriptTypeCount = nullptr;
		ManagedBridgeDetail::GetScriptTypeNameFn GetScriptTypeName = nullptr;
		ManagedBridgeDetail::CallOnInitFn CallOnInit = nullptr;
		ManagedBridgeDetail::CallOnStartFn CallOnStart = nullptr;
		ManagedBridgeDetail::CallOnUpdateFn CallOnUpdate = nullptr;
		ManagedBridgeDetail::DestroyInstanceFn DestroyInstance = nullptr;
		ManagedBridgeDetail::CallRenderFlowFn CallRenderFlow = nullptr;
	};
}
