#pragma once

#include "Classes/Object.h"
#include "Core/Core.h"
#include "Core/String/VspString.h"
#include "Core/Templates/ArrayList.h"
#include "Scripting/BridgeFunctions.h"

namespace Vsp
{
	// Non-negative integer handle addressing one managed script instance.
	// 0 means invalid (managed ids start at 1).
	using ScriptInstanceId = uint32;

	// -------------------------------------------------------------------------
	// ScriptEngine
	// -------------------------------------------------------------------------
	// Embeds the .NET CoreCLR runtime into the C++ host through the CoreCLR
	// Hosting API (nethost + hostfxr). The host:
	//   1. loads nethost.dll and asks it for the hostfxr.dll path,
	//   2. initializes hostfxr against a runtimeconfig.json,
	//   3. fetches raw function pointers into the managed bridge
	//      (VspEngine.NativeBridge, living in VspEngine.dll),
	//   4. loads the game Assembly (Assembly.dll - the assembly that holds
	//      the user scripts) through the managed bridge,
	//   5. enumerates the managed script types, GENERATES a non-negative
	//      InstanceID per instance, creates the native scene objects the
	//      instance is a reference handle for (a GameObject owning a Transform
	//      plus the script Component) and drives the lifecycle through the
	//      opaque IntPtr handle every managed ScriptBehaviour holds.
	// The reverse direction (C# -> C++) goes through the exports in
	// NativeExports.cpp / SceneExports.cpp / RhiExports.cpp, which managed code
	// reaches with DllImport.
	// All functions report failure through return values / outErrorText -
	// the engine never uses C++ exceptions.
	// -------------------------------------------------------------------------
#pragma warning(push)
#pragma warning(disable : 4251)   // ArrayList member: header-only template.
	class RUNTIME_API ScriptEngine
	{
	public:
		// One live script instance plus the native scene objects it addresses.
		struct ScriptInstanceEntry
		{
			ScriptInstanceId uInstanceId = 0;                     // Generated by this host; 0 = invalid.
			void* pManagedHandle = nullptr;                       // The managed ScriptBehaviour's IntPtr (GCHandle).
			NativeObjectHandle uGameObjectHandle = 0;             // The scene object the script is attached to.
			NativeObjectHandle uTransformHandle = 0;              // That object's transform.
			NativeObjectHandle uComponentHandle = 0;              // The script component itself.
		};

		static ScriptEngine& Get();

		// Loads nethost/hostfxr, initializes the runtime, resolves every
		// managed bridge entry point from the engine assembly (VspEngine.dll)
		// and loads the game Assembly (Assembly.dll) that holds the user
		// scripts. Call once before any script work.
		bool Initialize(
			const VspString& sEngineAssemblyPath,
			const VspString& sGameAssemblyPath,
			const VspString& sRuntimeConfigPath,
			const VspString& sDotNetRootPath,
			VspString& outErrorText);

		// Destroys every script instance (and its scene objects), lets the
		// managed render pipeline release its graphics resources and closes the
		// hostfxr context.
		void Shutdown();

		bool IsInitialized() const { return m_hHostFxrLibrary != nullptr; }

		// Asks the managed bridge for every concrete ScriptBehaviour type and
		// creates one instance of each with a host-generated InstanceID.
		// Returns false on failure.
		bool CreateAllScriptInstances(VspString& outErrorText);

		// Creates one instance of the given assembly-qualified type name; the
		// InstanceID is generated here on the C++ side.
		ScriptInstanceId CreateScriptInstance(const VspString& sTypeName);

		void CallScriptInit(ScriptInstanceId uInstanceId);
		void CallScriptStart(ScriptInstanceId uInstanceId);
		void CallScriptUpdate(ScriptInstanceId uInstanceId);
		void DestroyScriptInstance(ScriptInstanceId uInstanceId);

		// Invokes OnUpdate for every registered instance.
		void UpdateAllScripts();

		// Renders one frame through the managed frame driver
		// (VspEngine.Rendering.RenderFrameDriver): the engine's frame with the
		// active pipeline's passes inside it.
		void CallRenderFrame();

		// Lets the managed render pipeline release the graphics resources it
		// created through the wrapped graphics API.
		void ReleaseRenderPipeline();

		uint32 GetScriptInstanceCount() const { return static_cast<uint32>(m_ScriptInstances.GetSize()); }

		// InstanceID of the instance at the given position in the registry, or 0
		// when the index does not address one. The host walks this to run the
		// lifecycle of every instance it created.
		ScriptInstanceId GetScriptInstanceIdAt(uint32 uInstanceIndex) const
		{
			return (uInstanceIndex < m_ScriptInstances.GetSize())
				? m_ScriptInstances[uInstanceIndex].uInstanceId
				: 0;
		}

		// Game object handle of the instance at the given position (0 when the
		// index does not address one).
		NativeObjectHandle GetScriptGameObjectHandleAt(uint32 uInstanceIndex) const
		{
			return (uInstanceIndex < m_ScriptInstances.GetSize())
				? m_ScriptInstances[uInstanceIndex].uGameObjectHandle
				: k_nInvalidObjectHandle;
		}

		ScriptInstanceId GetPrimaryScriptInstanceId() const
		{
			return m_ScriptInstances.IsEmpty() ? 0 : m_ScriptInstances[0].uInstanceId;
		}
		NativeObjectHandle GetPrimaryScriptGameObjectHandle() const
		{
			return m_ScriptInstances.IsEmpty() ? 0 : m_ScriptInstances[0].uGameObjectHandle;
		}

	private:
		// The registry in Core/EngineServices.h owns this service's storage and
		// lifetime, so it has to be able to construct it.
		friend class EngineServices;

		ScriptEngine() = default;

		ScriptInstanceEntry* FindInstanceEntry(ScriptInstanceId uInstanceId);
		const ScriptInstanceEntry* FindInstanceEntry(ScriptInstanceId uInstanceId) const;

		bool LoadNetHostLibrary(const VspString& sDotNetRootPath, VspString& outErrorText);
		bool LoadHostFxrLibrary(VspString& outErrorText);
		bool InitializeHostFxrRuntime(const VspString& sRuntimeConfigPath, VspString& outErrorText);
		bool LoadManagedEntryPoints(const VspString& sEngineAssemblyPath, VspString& outErrorText);
		bool LoadGameAssembly(const VspString& sGameAssemblyPath, VspString& outErrorText);

		static bool FetchManagedEntryPoint(
			load_assembly_and_get_function_pointer_fn pLoadAssemblyFunction,
			const wchar_t* pAssemblyPathUtf16,
			const wchar_t* pTypeNameUtf16,
			const wchar_t* pMethodNameUtf16,
			void** ppOutFunction,
			VspString& outErrorText);

		// Native library handles (opaque void* - the platform-specific
		// loading lives in Common/PlatformMisc behind #if VSP_PLATFORM_WINDOWS).
		void* m_hNetHostLibrary = nullptr;
		void* m_hHostFxrLibrary = nullptr;
		hostfxr_handle m_RuntimeContext = nullptr;
		load_assembly_and_get_function_pointer_fn m_LoadAssemblyFunction = nullptr;
		BridgeFunctions m_BridgeFunctions;
		ArrayList<ScriptInstanceEntry> m_ScriptInstances;
		ScriptInstanceId m_nNextInstanceId = 1;   // 1-based; 0 means invalid.
	};
#pragma warning(pop)
}
