using System;

namespace VspEngine
{
	/// <summary>
	/// Unity-style behaviour component driven by the C++ host through the
	/// CoreCLR hosting bridge. The host creates one managed instance per script;
	/// the native scene holds the object the script is attached to (its
	/// GameObject, its Transform and this component), and the managed instance
	/// stores nothing but the handles addressing that data.
	///
	/// Lifecycle: OnInit -> OnStart -> OnUpdate* -> OnDestroy.
	/// </summary>
	public abstract class ScriptBehaviour : Component
	{
		/// <summary>
		/// Non-negative integer handle GENERATED by the C++ host to address this
		/// script instance (0 = invalid). It identifies the script, not a scene
		/// object: use <see cref="Object.NativeHandle"/>, <see cref="Component.GameObject"/>
		/// or <see cref="Component.Transform"/> to reach the scene data.
		/// </summary>
		public uint InstanceID { get; internal set; }

		/// <summary>
		/// Opaque pointer to this managed object (its GCHandle). The C++ host
		/// passes it back on every lifecycle call, which lets the bridge work
		/// without maintaining any instance registry of its own.
		/// </summary>
		public IntPtr NativePtr { get; internal set; }

		/// <summary>Called once by the host right after the instance is created.</summary>
		public virtual void OnInit() { }

		/// <summary>Called once by the host before the first OnUpdate.</summary>
		public virtual void OnStart() { }

		/// <summary>Called by the host every frame.</summary>
		public virtual void OnUpdate() { }

		/// <summary>Called by the host when the instance is destroyed.</summary>
		public virtual void OnDestroy() { }
	}
}
