param(
    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

# MSBuild's Exec task pipes the parent's stdin into this script; consume it so
# PowerShell never tries to bind that stream to the script parameters.
$input | Out-Null

$ErrorActionPreference = "Stop"

$shaderSourceDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# ---- Locate glslc.exe ---------------------------------------------------------
# Search order (nothing is ever written into Thirdparty - it is only read):
#   1. the project's own Thirdparty Vulkan SDK copy
#   2. the VULKAN_SDK environment variable
#   3. a machine-wide C:\VulkanSDK install
$thirdPartyGlslc = Join-Path $shaderSourceDir "..\..\..\..\Thirdparty\Vulkan\Bin\glslc.exe"
$candidates = @()
if (Test-Path $thirdPartyGlslc) {
    $candidates += $thirdPartyGlslc
}
if ($env:VULKAN_SDK) {
    $candidates += Join-Path $env:VULKAN_SDK "Bin\glslc.exe"
}
$candidates += @(Get-ChildItem "C:\VulkanSDK\*\Bin\glslc.exe" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName)

$glslc = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $glslc) {
    throw "glslc.exe not found - place the Vulkan SDK in Engine\Source\Thirdparty\Vulkan, install it, or set VULKAN_SDK."
}

# Bindless (Vulkan 1.3) is the only supported rendering path, so only its
# shaders are compiled and embedded.
$shaderNames = @(
    "TriangleBindless.vert",
    "TriangleBindless.frag"
)

# ---- Incremental check: skip when the header is newer than every input --------
$inputs = @($MyInvocation.MyCommand.Path) + ($shaderNames | ForEach-Object { Join-Path $shaderSourceDir $_ })
if ((Test-Path $OutputPath) -and (Test-Path $glslc)) {
    $outputTime = (Get-Item $OutputPath).LastWriteTimeUtc
    $upToDate = $true
    foreach ($input in $inputs) {
        if ((Get-Item $input).LastWriteTimeUtc -gt $outputTime) {
            $upToDate = $false
            break
        }
    }
    if ($upToDate) {
        Write-Host "CompileShaders: $OutputPath is up to date."
        exit 0
    }
}

Write-Host "CompileShaders: using $glslc"

# ---- Compile each shader to a temporary SPIR-V file --------------------------
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Auto-generated by CompileShaders.ps1 - do not edit.")
$lines.Add("#pragma once")
$lines.Add("")
$lines.Add("#include <cstdint>")
$lines.Add("")
$lines.Add("namespace Vsp")
$lines.Add("{")
$lines.Add("    namespace Shaders")
$lines.Add("    {")

foreach ($shaderName in $shaderNames) {
    $shaderPath = Join-Path $shaderSourceDir $shaderName
    $spvPath = Join-Path $env:TEMP ("vsp_" + $shaderName + ".spv")

    & $glslc $shaderPath -o $spvPath
    if ($LASTEXITCODE -ne 0) {
        throw "glslc failed to compile $shaderName"
    }

    $bytes = [System.IO.File]::ReadAllBytes($spvPath)
    if (($bytes.Length % 4) -ne 0) {
        throw "SPIR-V size for $shaderName is not 4-byte aligned"
    }

    $wordCount = [int]($bytes.Length / 4)
    $symbolName = "k_" + $shaderName.Replace(".", "_") + "Spv"
    $sizeName = "k_n" + $shaderName.Replace(".", "_") + "SpvSize"

    $lines.Add("        inline const uint32_t $symbolName[] = {")

    $chunks = New-Object System.Collections.Generic.List[string]
    for ($wordIndex = 0; $wordIndex -lt $wordCount; $wordIndex++) {
        $word = [System.BitConverter]::ToUInt32($bytes, $wordIndex * 4)
        $chunks.Add(("0x{0:X8}" -f $word))
        if ($chunks.Count -eq 8) {
            $lines.Add("            " + ($chunks -join ", ") + ",")
            $chunks.Clear()
        }
    }
    if ($chunks.Count -gt 0) {
        $lines.Add("            " + ($chunks -join ", "))
    }
    $lines.Add("        };")
    $lines.Add("        inline constexpr uint32_t $sizeName = $wordCount;")
    $lines.Add("")
    Remove-Item $spvPath -Force
}

$lines.Add("    }")
$lines.Add("}")

$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}
[System.IO.File]::WriteAllLines($OutputPath, $lines, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "CompileShaders: wrote $OutputPath"
