#pragma once

#include <cstdint>

#include <nethost.h>
#include <hostfxr.h>
#include <coreclr_delegates.h>

namespace Vsp
{
	// -------------------------------------------------------------------------
	// BridgeFunctions
	// -------------------------------------------------------------------------
	// Raw function pointers into the managed bridge (VspEngine.NativeBridge in
	// VspPlayer.dll), fetched through hostfxr's
	// load_assembly_and_get_function_pointer. Every managed entry point is
	// marked [UnmanagedCallersOnly], so the pointers follow the platform
	// calling convention (STDMETHODCALLTYPE == the native default on x64).
	//
	// Ownership model: the C++ host GENERATES the non-negative InstanceID and
	// receives back an opaque native handle (the managed object's GCHandle as
	// an IntPtr). Lifecycle calls pass that handle - the managed bridge keeps
	// no instance registry of its own.
	// -------------------------------------------------------------------------

	namespace ManagedBridgeDetail
	{
		// Creates one script instance. nInstanceId is generated by the C++
		// host; the returned handle addresses the managed object afterwards.
		using CreateInstanceFn = void* (STDMETHODCALLTYPE*)(
			int32 nInstanceId,
			const char_t* pTypeNameUtf16);

		// Script type enumeration (the host decides what to instantiate).
		using GetScriptTypeCountFn = int32 (STDMETHODCALLTYPE*)();
		using GetScriptTypeNameFn = void (STDMETHODCALLTYPE*)(
			int32 nTypeIndex,
			char_t* pBufferUtf16,
			int32 nBufferCapacityUnits);

		// Lifecycle calls, addressed through the opaque managed handle.
		using CallOnInitFn = void (STDMETHODCALLTYPE*)(void* pManagedHandle);
		using CallOnStartFn = void (STDMETHODCALLTYPE*)(void* pManagedHandle);
		using CallOnUpdateFn = void (STDMETHODCALLTYPE*)(void* pManagedHandle);
		using DestroyInstanceFn = void (STDMETHODCALLTYPE*)(void* pManagedHandle);
	}

	struct BridgeFunctions
	{
		ManagedBridgeDetail::CreateInstanceFn CreateInstance = nullptr;
		ManagedBridgeDetail::GetScriptTypeCountFn GetScriptTypeCount = nullptr;
		ManagedBridgeDetail::GetScriptTypeNameFn GetScriptTypeName = nullptr;
		ManagedBridgeDetail::CallOnInitFn CallOnInit = nullptr;
		ManagedBridgeDetail::CallOnStartFn CallOnStart = nullptr;
		ManagedBridgeDetail::CallOnUpdateFn CallOnUpdate = nullptr;
		ManagedBridgeDetail::DestroyInstanceFn DestroyInstance = nullptr;
	};
}
